"""Add custom popularity

Revision ID: e3a414cf0342
Revises: 
Create Date: 2020-05-30 13:28:00.898359

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e3a414cf0342"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("song", sa.Column(
        "custom_popularity", sa.Float(), nullable=True))
    op.drop_column("song", "yt_popularity")
    op.add_column("user_posts", sa.Column(
        "permalink_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_posts", "permalink_url")
    op.add_column(
        "song",
        sa.Column(
            "yt_popularity",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("song", "custom_popularity")
    # ### end Alembic commands ###
